mariadb:
  enabled: false

fullnameOverride: wordpress

externalDatabase:
  host: 10.20.71.10
  port: 3306
  user: wp_user
  password: "wp_db"
  database: wordpress
  #existingSecret: "wp-db" # si tu veux passer par un secret, cl√©: mariadb-password

service:
  type: ClusterIP

persistence:
  enabled: true
  existingClaim: wp-pvc

ingress:
  enabled: true
  ingressClassName: traefik
  hostname: wp-lab.local
